name: Build & Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: abivarmang/sample_app
      IMAGE_TAG: latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Set up kubeconfig for Minikube
        run: |
          mkdir -p $HOME/.kube
          echo "
          apiVersion: v1
          kind: Config
          clusters:
          - name: minikube
            cluster:
              server: https://${{secrets.KUBE_SERVER}}:8443
              certificate-authority-data: ${{ secrets.KUBE_CA }}
          contexts:
          - name: minikube
            context:
              cluster: minikube
              user: minikube
          current-context: minikube
          users:
          - name: minikube
            user:
              client-certificate-data: ${{ secrets.KUBE_CLIENT_CERT }}
              client-key-data: ${{ secrets.KUBE_CLIENT_KEY }}
          " > $HOME/.kube/config

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/manifest.yml
          kubectl rollout status deployment/sample_app

